apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mongodb-sharded.fullname" . }}
  labels: {{- include "mongodb-sharded.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- if .Values.mongodbRootPassword }}
  mongodb-root-password: {{ .Values.mongodbRootPassword | b64enc | quote }}
  {{- else }}
  mongodb-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if and .Values.mongodbUsername .Values.mongodbDatabase }}
  {{- if .Values.mongodbPassword }}
  mongodb-password: {{ .Values.mongodbPassword | b64enc | quote }}
  {{- else }}
  mongodb-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if .Values.replicaSetKey }}
  mongodb-replica-set-key: {{ .Values.replicaSetKey | b64enc | quote }}
  {{- else }}
  mongodb-replica-set-key: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
